hot-reload: false # автоматически перезагружать конфиги при изменениях

# Здесь можете назначить команды для открытия меню
open_commands:
  bmenu_seller:
    aliases:
      - bseller
    menu: example:seller
    permission: ~ # не обязательный параметр
  bmenu_kick:
    menu: example:kick
    tab-completer:
      PLAYER:
        type: player
        exx: [ ]

# все виды аргуметов
tab-completer:
  PLAYER:
    type: player # ник игрока
  INT:
    type: int # число
  BOOL:
    type: bool # true/false
  CHOICE:
    type: choice # список на выбор
    items: # при вводе команды будет выведен этот список
      - 'hub'
      - 'shop'
      - 'что-то'
  DOUBLE:
    type: double # число с плавающей точкой
  LONG:
    type: long # большое число
  STRING:
    type: string # любая строка