name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Jars
          path: target/*.jar
